### ISSUE TITLE
Decide on Gilson issue relating to SAMPL challenges across aims

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/SAMPL-R01#26]
He raised the issue of why we give plans for SAMPL in Aims 1-3, and wondered whether the info on the actual plans should be provided in Aim 4 to give a comprehensive picture of what is planned.

I did add text clarifying that we are talking, in Aims 1-3, about collecting the data for those challenges.

My thought is that we shouldn't do any sort of drastic reorganization here, as if we bring all of the info on specific data sets together into Aim 4 we won't really have significant content in AIms 1-3. I think we (a) just need to be clear we're talking about gathering the data (I'm adjusting the language along these lines) and (b) rely on the Timeline more (especially now that I'm putting it earlier) to make this more clear throughout.

**Comment by jchodera** [comment]
What you suggest is the right approach for us at this stage.
