### ISSUE TITLE
Include evidence Chodera lab can do proposed experiments

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/SAMPL-R01#27]
- Figure needs updating with their data
- Any updates to text to provide evidence will help too

**Comment by jchodera** [comment]
Mehtap is working on incorporating our experimental data into the figure.
We should have it by early afternoon on Friday.

**Comment by davidlmobley** [comment]
Do you have anything you want to do to the text as well (i.e. in the locations Mike highlighted)?

**Comment by jchodera** [comment]
I'll update the text and caption after the figure is updated.

**Comment by davidlmobley** [comment]
This figure went in and the text was adjusted slightly; closing
