### ISSUE TITLE
Add webinars to timeline?

### ISSUE THREAD

**Issue by davidlmobley** [choderalab/SAMPL-R01#29]
MKG suggested adding webinars to timeline. Possibly we should have these during the years we don't have an overall D3R meeting.

**Comment by jchodera** [comment]
"Webinars"? As in "someone gives a talk and other people can tune in"?

Does this add a lot beyond the virtual meetings?

**Comment by jchodera** [comment]
I guess I'd rather see toolbuilders who are doing well at something (like
protonation state prediction, etc.) give little tutorials on how to use the
tools or methods so that they can be incorporated more broadly. Is there a
better way to support that?

**Comment by jchodera** [comment]
Let's just say I've never actually head anyone get excited about webinars.
Can we do better?

**Comment by davidlmobley** [comment]
Whatever you want to call it, the point I would want to deal with is that right now we have people from the individual aims (SAMPL challenges on each topic) who will talk to each other at least once a year, but we only have crossover between the different topics at the D3R meetings, which are once every 2 years roughly. So if someone learns something crucial on how to, say, better predict protonation states from the physical property challenge, the people working on host-guest binding won't necessarily hear about it for up to two years... They MIGHT (i.e. if they join the relevant slack channel, get a preprint of a paper, etc.) but it's not for sure. So, there might be a lot of room for regularly scheduled virtual meetings across the whole challenge that focus on key lessons learned/how to approach the next set of challenges.

As a participant, I think that would be something I would need, whether it's called a "webinar" or not.

**Comment by jchodera** [comment]
> we only have crossover between the different topics at the D3R meetings, which are once every 2 years roughly.

Whoa, I hadn't realized that.

OK, maybe a "webinar" isn't a bad idea. We can pick a few teams from each challenge to give talks about the lessons they learned to the whole SAMPL/D3R/comp chem audience, either via virtual meetings or ACS sessions with recorded talks / distributed slides.

**Comment by davidlmobley** [comment]
Just pushed to my PR.
